### ISSUE TITLE
segfault in main

### ISSUE THREAD

**Issue by n0izn0iz** [grafana/cuetsy#46]
## Da problem

```
❯ cuetsy monolith.cue
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1204078]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0x2, 0xdde26ece00000003)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/adt/eval.go:911 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc000222b60, 0x0, 0x5)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/adt/eval.go:172 +0x4e
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/adt/composite.go:445
cuelang.org/go/cue.(*Instance).Value(0xc000465ce0)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.0/cue/instance.go:214 +0x85
main.main()
	/Users/norman/go/pkg/mod/github.com/grafana/cuetsy@v0.0.0-20220107153554-485eef9da816/cmd/cuetsy/main.go:40 +0x2ba
```

## monolith.cue

Generated using
```
cue get go github.com/ipfs/go-ipfs-config
go run ./cmd/aggregate-cues cue.mod/gen/**/*.cue > monolith.cue
```

- [aggregate-cues](https://gist.github.com/n0izn0iz/de24032f77bccc830c2b25702ee2a96d) source
- final [monolith.cue](https://gist.github.com/n0izn0iz/44eafc0125d634ae9f5adb42a066f27a)

```
❯ cue version
cue version v0.4.1-rc.2 darwin/amd64
```
```
❯ go version
go version go1.17.1 darwin/amd64
```

**Comment by sdboyer** [comment]
i think you're looking for cue-lang/cue to file this against.
